const ChannelTypes = {
	GET_CHANNELS_START: 'GET_CHANNELS_START',
	GET_CHANNELS_SUCCESS: 'GET_CHANNELS_SUCCESS',
	GET_CHANNELS_FAILURE: 'GET_CHANNELS_FAILURE',
	GET_CHANNEL_DETAILS_START: 'GET_CHANNEL_DETAILS_START',
	GET_CHANNEL_DETAILS_SUCCESS: 'GET_CHANNEL_DETAILS_SUCCESS',
	GET_CHANNEL_DETAILS_FAILURE: 'GET_CHANNEL_DETAILS_FAILURE',
};

export default ChannelTypes;
